version: '3.4'

services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgis
    environment:
      POSTGRES_DB: db_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - "5432:5432"
    restart: "no"