version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgis
    environment:
      POSTGRES_DB: db_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "no"
    networks:
      - app-network

  learniverse-api:
    container_name: learniverse-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - postgis
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge