worker_processes auto;

events {
  worker_connections 1024;
}

rtmp {
  server {
    listen 1935;
    chunk_size 4000;

    application live {
      live on;

      on_publish http://localhost:8080/api/live/start;
      on_publish_done http://localhost:8080/api/live/end;

      push rtmp://localhost:1936/process;

      deny play all;
    }
  }

  server {
    listen 1936;
    application process {
      live on;
      allow publish 127.0.0.1;
      allow play all;
      deny publish all;
    }
  }
}